- name : download repo
  ansible.builtin.yum :
    name : https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state : installed
    disable_gpg_check : true

- name : enable redis
  ansible.builtin.shell : yum module enable redis:remi-6.2 -y

- name : install redis
  ansible.builtin.yum :
    name : redis
    state : installed

- name : change ip address
  ansible.builtin.replace :
    path : /etc/redis.conf
    regexp : '127.0.0.1'
    replace : '0.0.0.0'

- name : change ip address
  ansible.builtin.replace:
    path : /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name : start redis
  ansible.builtin.systemd :
    name : redis
    state : restarted
    enabled : yes