- name: copy cart service
  ansible.builtin.copy:
    src : cart.service
    dest : /etc/systemd/system/cart.service

- name : download repos
  ansible.builtin.shell : curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name : install nodejs
  ansible.builtin.yum :
    name : nodejs
    state : installed

- name : add user
  ansible.builtin.user :
    name : roboshop

- name : delete old directory
  ansible.builtin.file :
    path : /app
    state : absent

- name : create new directory
  ansible.builtin.file:
    path: /app
    state: directory

- name : unarchive file
  ansible.builtin.unarchive :
    src : https://roboshop-artifacts.s3.amazonaws.com/cart.zip
    dest : /app
    remote_src : yes

- name :  install depedencies
  ansible.builtin.shell : npm install
  args :
    chdir : /app

- name : start cart
  ansible.builtin.systemd :
    name : cart
    state : restarted
    enabled : yes
    daemon-reload : yes